[package]
name = "zec_bridge"
type = "contract"
authors = ["Null-Gravity Bridge"]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v3.0.0-nightly.20251128", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v3.0.0-nightly.20251128", directory = "noir-projects/aztec-nr/uint-note" }
